### ISSUE TITLE
How to fix ?

### ISSUE THREAD

**Issue by Suspectxyzz** [not-wlan/regionpicker#1]
[code]
error[E0463]: can't find crate for `protoc_rust`
 --> build.rs:1:1
  |
1 | extern crate protoc_rust;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
[/code]
  build.rs:1:1 --->extern crate protoc_rust;

how to fix ?
https://prnt.sc/rocqqi

**Comment by not-wlan** [comment]
Use `cargo build` instead of calling rustc directly.

**Comment by Suspectxyzz** [comment]
still does not work, can you give me a more candid advice?
![okkk](https://user-images.githubusercontent.com/45514952/77851914-60477780-71e4-11ea-8aa4-db04e3c3616e.png)

https://prnt.sc/rovehl

**Comment by not-wlan** [comment]
Read the error message, it tells you to install `protoc`, the Protobuf compiler.
